apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: node-container
        image: ahmedgamal22/myapp
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-app
